version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram_bot
      PGDATA: /var/lib/postgres/data/
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgres/data/

volumes:
  db: